# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
        os: [windows-latest]
        # os: [windows-latest, macos-latest]

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 进入前端项目frontend
      run: cd frontend && ls

    - name: 打印前端
      run: cd frontend && ls

    - name: 安装前端依赖
      run: cd frontend && npm i
      
    - name: 打包前端
      run: cd frontend && npm run build   

    # - name: 返回主目录
    #   run: cd ..

    - name: 安装依赖
      run: npm i  

    - name: 复制前端dist
      run: npm run rd

    - name: 打包windows
      run: npm run build-w
      env:
          GH_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    - uses: actions/upload-artifact@v2
      name: upload build output
      with:
        name: 下载的压缩包名字
        path: ${{ github.workspace }}/out
        retention-days: 1

    # - name: 打包mac
    #   run: npm run build-m
    
    # - name: Publish release
    # # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    #   # 编辑 Releases 草稿并发布
    #   run: gh release edit ${{ github.ref_name }} --draft=false
    #   env:
    #     GH_TOKEN: ${{ secrets.CODECOV_TOKEN }}    
  
  release:
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        # 编辑 Releases 草稿并发布
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.CODECOV_TOKEN }}